begin;

create table if not exists public.bot_feedback (
  id bigint generated by default as identity primary key,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete restrict,
  telegram_id bigint not null,
  employee_name text not null,
  kind text not null check (kind in ('suggestion', 'complaint', 'problem')),
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists bot_feedback_created_idx on public.bot_feedback (created_at desc);
alter table public.bot_feedback enable row level security;
revoke all on public.bot_feedback from anon, authenticated;

create or replace function public.feedback_submit(p_actor_id bigint, p_kind text, p_message text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_employee public.employee_profiles%rowtype;
  v_row public.bot_feedback%rowtype;
begin
  if p_kind not in ('suggestion', 'complaint', 'problem') then
    raise exception 'Unsupported feedback kind' using errcode = '22023';
  end if;
  if char_length(trim(coalesce(p_message, ''))) not between 1 and 2000 then
    raise exception 'Сообщение должно содержать от 1 до 2000 символов' using errcode = '22023';
  end if;
  select * into v_employee from public.employee_profiles
  where telegram_id = p_actor_id and activation_status = 'active'
  order by activated_at desc nulls last, id desc limit 1;
  if not found then raise exception 'Требуется активный профиль сотрудника' using errcode = '42501'; end if;

  insert into public.bot_feedback (employee_profile_id, telegram_id, employee_name, kind, message)
  values (v_employee.id, p_actor_id, v_employee.full_name, p_kind, trim(p_message))
  returning * into v_row;
  return to_jsonb(v_row);
end;
$$;

create or replace function public.feedback_list(p_actor_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.schedule_is_admin(p_actor_id) then
    raise exception 'Only managers can read feedback' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(to_jsonb(f) order by f.created_at desc), '[]'::jsonb) from public.bot_feedback f);
end;
$$;

revoke all on function public.feedback_submit(bigint,text,text) from public;
revoke all on function public.feedback_list(bigint) from public;
grant execute on function public.feedback_submit(bigint,text,text) to anon, authenticated;
grant execute on function public.feedback_list(bigint) to anon, authenticated;

commit;

-- Verification:
-- select to_regprocedure('public.feedback_submit(bigint,text,text)');
-- select to_regprocedure('public.feedback_list(bigint)');
