begin;

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  chat_id bigint not null,
  thread_id bigint,
  recipient_ids jsonb not null default '[]'::jsonb,
  audience text not null default 'selected' check (audience in ('all', 'selected')),
  repeat_hours integer check (repeat_hours between 1 and 168),
  next_send_at timestamptz not null default now(),
  last_sent_at timestamptz,
  is_active boolean not null default true,
  created_by bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_notifications_due_idx on public.admin_notifications (is_active, next_send_at);
alter table public.admin_notifications enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'admin_notifications' and policyname = 'admin_notifications_admin_access') then
    create policy admin_notifications_admin_access on public.admin_notifications
      for all to authenticated
      using ((auth.jwt() -> 'app_metadata' ->> 'admin_role') in ('super_admin', 'restaurant_admin'))
      with check ((auth.jwt() -> 'app_metadata' ->> 'admin_role') in ('super_admin', 'restaurant_admin'));
  end if;
end
$$;

revoke all on public.admin_notifications from anon;
grant select, insert, update, delete on public.admin_notifications to authenticated;
grant usage, select on sequence public.admin_notifications_id_seq to authenticated;

commit;

-- Verification:
-- select to_regclass('public.admin_notifications');
