begin;

create table if not exists public.schedule_weeks (
  id bigint generated by default as identity primary key,
  week_start date not null unique,
  submission_deadline timestamptz not null,
  status text not null default 'collecting' check (status in ('collecting', 'published')),
  created_by bigint,
  published_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_entries (
  id bigint generated by default as identity primary key,
  week_id bigint not null references public.schedule_weeks(id) on delete cascade,
  employee_profile_id bigint not null references public.employee_profiles(id) on delete cascade,
  employee_telegram_id bigint not null,
  employee_name text not null,
  availability jsonb not null default '{}'::jsonb,
  final_schedule jsonb not null default '{}'::jsonb,
  comment text not null default '',
  submitted_at timestamptz,
  updated_by bigint,
  updated_at timestamptz not null default now(),
  unique (week_id, employee_profile_id)
);

create index if not exists schedule_entries_week_idx
  on public.schedule_entries (week_id, employee_name);
create index if not exists schedule_entries_employee_idx
  on public.schedule_entries (employee_profile_id, week_id);

alter table public.schedule_weeks enable row level security;
alter table public.schedule_entries enable row level security;
revoke all on public.schedule_weeks, public.schedule_entries from anon, authenticated;

create or replace function public.schedule_is_admin(p_actor_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select p_actor_id = 818748106
    or exists (select 1 from public.managers m where m.telegram_id = p_actor_id);
$$;

create or replace function public.schedule_ensure_week(p_actor_id bigint, p_week_start date)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week_id bigint;
begin
  if extract(isodow from p_week_start) <> 1 then
    raise exception 'week_start must be Monday' using errcode = '22007';
  end if;
  if not public.schedule_is_admin(p_actor_id)
     and not exists (
       select 1 from public.employee_profiles ep
       where ep.telegram_id = p_actor_id and ep.activation_status = 'active'
     ) then
    raise exception 'Active employee profile required' using errcode = '42501';
  end if;

  insert into public.schedule_weeks (week_start, submission_deadline, created_by)
  values (
    p_week_start,
    ((p_week_start - 5) + time '23:59') at time zone 'Europe/Moscow',
    p_actor_id
  )
  on conflict (week_start) do update set week_start = excluded.week_start
  returning id into v_week_id;
  return v_week_id;
end;
$$;

create or replace function public.schedule_get_week(p_actor_id bigint, p_week_start date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week public.schedule_weeks%rowtype;
  v_is_admin boolean := public.schedule_is_admin(p_actor_id);
  v_entries jsonb;
begin
  perform public.schedule_ensure_week(p_actor_id, p_week_start);
  select * into v_week from public.schedule_weeks where week_start = p_week_start;

  select coalesce(jsonb_agg(item order by item->>'employee_name'), '[]'::jsonb)
  into v_entries
  from (
    select jsonb_build_object(
      'employee_profile_id', ep.id,
      'employee_telegram_id', ep.telegram_id,
      'employee_name', ep.full_name,
      'availability', coalesce(se.availability, '{}'::jsonb),
      'final_schedule', coalesce(se.final_schedule, '{}'::jsonb),
      'comment', coalesce(se.comment, ''),
      'submitted_at', se.submitted_at,
      'updated_at', se.updated_at
    ) as item
    from public.employee_profiles ep
    left join public.schedule_entries se
      on se.week_id = v_week.id and se.employee_profile_id = ep.id
    where ep.activation_status = 'active'
      and ep.telegram_id is not null
      and (v_is_admin or ep.telegram_id = p_actor_id)
  ) rows_for_actor;

  return jsonb_build_object(
    'week', to_jsonb(v_week),
    'is_admin', v_is_admin,
    'can_submit', v_is_admin or (v_week.status = 'collecting' and now() <= v_week.submission_deadline),
    'entries', v_entries
  );
end;
$$;

create or replace function public.schedule_save_entry(
  p_actor_id bigint,
  p_week_start date,
  p_employee_profile_id bigint,
  p_mode text,
  p_values jsonb,
  p_comment text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week public.schedule_weeks%rowtype;
  v_employee public.employee_profiles%rowtype;
  v_is_admin boolean := public.schedule_is_admin(p_actor_id);
  v_entry public.schedule_entries%rowtype;
begin
  if p_mode not in ('availability', 'final') then
    raise exception 'Unsupported schedule mode' using errcode = '22023';
  end if;
  perform public.schedule_ensure_week(p_actor_id, p_week_start);
  select * into v_week from public.schedule_weeks where week_start = p_week_start;
  select * into v_employee from public.employee_profiles
    where id = p_employee_profile_id and activation_status = 'active';
  if not found then
    raise exception 'Employee not found' using errcode = 'P0002';
  end if;
  if not v_is_admin and v_employee.telegram_id <> p_actor_id then
    raise exception 'Employees can edit only their own row' using errcode = '42501';
  end if;
  if not v_is_admin and (p_mode <> 'availability' or v_week.status <> 'collecting' or now() > v_week.submission_deadline) then
    raise exception 'Submission deadline has passed' using errcode = '42501';
  end if;

  insert into public.schedule_entries (
    week_id, employee_profile_id, employee_telegram_id, employee_name,
    availability, final_schedule, comment, submitted_at, updated_by
  ) values (
    v_week.id, v_employee.id, v_employee.telegram_id, v_employee.full_name,
    case when p_mode = 'availability' then coalesce(p_values, '{}'::jsonb) else '{}'::jsonb end,
    case when p_mode = 'final' then coalesce(p_values, '{}'::jsonb) else '{}'::jsonb end,
    coalesce(p_comment, ''), now(), p_actor_id
  )
  on conflict (week_id, employee_profile_id) do update set
    availability = case when p_mode = 'availability' then excluded.availability else schedule_entries.availability end,
    final_schedule = case when p_mode = 'final' then excluded.final_schedule else schedule_entries.final_schedule end,
    comment = excluded.comment,
    submitted_at = case when p_mode = 'availability' then now() else schedule_entries.submitted_at end,
    updated_by = p_actor_id,
    updated_at = now()
  returning * into v_entry;

  update public.schedule_weeks set updated_at = now() where id = v_week.id;
  return to_jsonb(v_entry);
end;
$$;

create or replace function public.schedule_list_weeks(p_actor_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_admin boolean := public.schedule_is_admin(p_actor_id);
  v_profile_id bigint;
begin
  if not v_is_admin then
    select id into v_profile_id from public.employee_profiles
      where telegram_id = p_actor_id and activation_status = 'active';
    if v_profile_id is null then
      raise exception 'Active employee profile required' using errcode = '42501';
    end if;
  end if;
  return (
    select coalesce(jsonb_agg(to_jsonb(sw) order by sw.week_start desc), '[]'::jsonb)
    from public.schedule_weeks sw
    where v_is_admin
       or sw.status = 'published'
       or exists (
         select 1 from public.schedule_entries se
         where se.week_id = sw.id and se.employee_profile_id = v_profile_id
       )
  );
end;
$$;

create or replace function public.schedule_publish_week(p_actor_id bigint, p_week_start date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week public.schedule_weeks%rowtype;
begin
  if not public.schedule_is_admin(p_actor_id) then
    raise exception 'Only an admin can publish schedules' using errcode = '42501';
  end if;
  update public.schedule_weeks
  set status = 'published', published_at = now(), updated_at = now()
  where week_start = p_week_start
  returning * into v_week;
  if not found then raise exception 'Week not found' using errcode = 'P0002'; end if;
  return to_jsonb(v_week);
end;
$$;

revoke all on function public.schedule_is_admin(bigint) from public;
revoke all on function public.schedule_ensure_week(bigint, date) from public;
grant execute on function public.schedule_get_week(bigint, date) to anon, authenticated;
grant execute on function public.schedule_save_entry(bigint, date, bigint, text, jsonb, text) to anon, authenticated;
grant execute on function public.schedule_list_weeks(bigint) to anon, authenticated;
grant execute on function public.schedule_publish_week(bigint, date) to anon, authenticated;

commit;

-- Verification:
-- select to_regprocedure('public.schedule_get_week(bigint,date)');
-- select to_regprocedure('public.schedule_save_entry(bigint,date,bigint,text,jsonb,text)');
